### PR TITLE
Add `python_arch` input option

### PR DESCRIPTION
**Pull request by Young-Lord**

### CODE REVIEW

**Comment by sayyid5416** [comment]
It seems like arch was **not used** in pyinstaller command.

**Comment by Young-Lord** [comment]
PyInstaller's arch depends on Python arch.

**Comment by sayyid5416** [comment]
@Young-Lord Have you tested this change properly?

**Comment by Young-Lord** [comment]
Yes. I have confirmed this works properly.
Example: https://github.com/Young-Lord/QQ-History-Backup/actions/runs/4645432036
successfully build a `x86` exe, with requirements `requests` and `tkinter`

**Comment by Young-Lord** [comment]
Yes. I have confirmed this works properly.
Example: https://github.com/Young-Lord/QQ-History-Backup/actions/runs/4645432036
successfully build a `x86` exe, with requirements `requests` and `tkinter`

example

**Comment by sayyid5416** [comment]
Thanks for confirming. I'll do a few tests and then merge it.

**Review by sayyid5416 — APPROVED** [review]

**Pull request merged**
